In [32]:
from __future__ import print_function
import torch

In [33]:
import numpy as np


In [34]:
from __future__ import print_function
import torch


In [35]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
import torch

In [38]:
import numpy as np
b = np.arange(12).reshape(4,3)           # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
 a = np.arange(6)                         # 1d array
print(a)

In [ ]:
print(np.arange(10000))


In [ ]:
import torch

In [ ]:
import torch

In [ ]:
import numpy as np
a = np.arange(0,1000,2)
b = np.linspace(0,1000,1001)
b


In [39]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
b.sum(axis = 1)

array([ 6, 22, 38])

In [41]:
b.cumsum(axis = 1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [43]:
B = np.arange(3)
B

array([0, 1, 2])

In [44]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [45]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [47]:
C = np.array([2.,-1.,4.])
np.add(B,C)

array([2., 0., 6.])

In [48]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [49]:
a[2]

8

In [50]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [53]:
a[:6:2] = 1000#什么意思？
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [54]:
a[: : -1]#reverse a

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [56]:
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [57]:
for i in a:
    print(i**(1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [61]:
def f(x,y):
 return 10*x+y

In [64]:
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [65]:
b[2,3]

23

In [66]:
b[0:5,1] # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [67]:
b[:,1]

array([ 1, 11, 21, 31, 41])

In [68]:
b[1:3,:]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [69]:
b[-1] # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

In [70]:
b[-1,...]

array([40, 41, 42, 43])

In [75]:
c = np.array([[[0,1,2],[10,12,13]],
              [[100,101,102],[110,112,113]]])

In [76]:
c.shape

(2, 2, 3)

In [77]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [78]:
c[...,2]

array([[  2,  13],
       [102, 113]])

In [79]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [82]:
for element in b.flat:
 print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [83]:
for element in c.flat:
 print(element)

0
1
2
10
12
13
100
101
102
110
112
113


In [89]:
rg = np.random.default_rng(1)
a  = np.floor(10*rg.random((3,4)))#floor()返回目标的下舍整数
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [90]:
a.shape

(3, 4)

In [91]:
a.ravel()# returns the array, flattened返回展开数组

array([5., 9., 1., 9., 3., 4., 8., 4., 5., 0., 7., 5.])

In [92]:
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [93]:
a.reshape(6,2)#不改变数据的条件下修改形状

array([[5., 9.],
       [1., 9.],
       [3., 4.],
       [8., 4.],
       [5., 0.],
       [7., 5.]])

In [94]:
a.T#转置矩阵

array([[5., 3., 5.],
       [9., 4., 0.],
       [1., 8., 7.],
       [9., 4., 5.]])

In [95]:
a.T.shape

(4, 3)

In [97]:
a.resize((2,6))#与reshape不同，resize修改的是数组本身
a

array([[5., 9., 1., 9., 3., 4.],
       [8., 4., 5., 0., 7., 5.]])

In [98]:
a

array([[5., 9., 1., 9., 3., 4.],
       [8., 4., 5., 0., 7., 5.]])

In [102]:
a.reshape(3,-1)

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])